### ISSUE TITLE
Descobrir porque na hospedagem do site o firebase não indentifica o UTF-8.

### ISSUE THREAD

**Issue by Paulo-Bezerra** [Paulo-Bezerra/Arena-To-Play#6]
É upado o arquivo, mas ao chegar ao servidor ele modifica as letras *latinas* para caractere de interrogação.

**Comment by DicksonSilva** [comment]
É necessário que o editor de texto esteja configurado de acordo com a codificação do  ***'UTF-8'*** para a criação do texto, pois é assim que o *firebase* reconhece a **codificação** dos arquivos.
